name: login
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  lottie: ^2.6.0
  get: ^4.6.5
  page_transition: ^2.0.9
  otp_text_field: ^1.1.3
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

