// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Rbdma-MIStcVFnZ3R5pQmfNqiIn0MII',
    appId: '1:199182362407:web:637788152bfe9edaee6b02',
    messagingSenderId: '199182362407',
    projectId: 'login-template-7eacb',
    authDomain: 'login-template-7eacb.firebaseapp.com',
    storageBucket: 'login-template-7eacb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJcFVgRNbjmKuncJXXA7iV8WH5TSXbhM',
    appId: '1:199182362407:android:9d5c539573080782ee6b02',
    messagingSenderId: '199182362407',
    projectId: 'login-template-7eacb',
    storageBucket: 'login-template-7eacb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACUqbeMkOrGJgnhzAYS65cwECX8gy49YE',
    appId: '1:199182362407:ios:b5a018b4700b1cd4ee6b02',
    messagingSenderId: '199182362407',
    projectId: 'login-template-7eacb',
    storageBucket: 'login-template-7eacb.appspot.com',
    iosClientId: '199182362407-s9r5umi5o4354iqptt0vu55p1s1u1ure.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
